branch-defaults:
  master:
    environment: development
global:
  application_name: iotme
  branch: master
  default_ec2_keyname: null
  default_platform: Ruby 2.4 (Puma)
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
